### PR TITLE
Update Radar SDK to version 2.0.0

### PR DESCRIPTION
**Pull request by russellcullen**

### CODE REVIEW

**Review by samdozor — APPROVED** [review]
This looks good. In the future it would be great if you could update to using the newer identity and user attribute APIs. As I understand it this PR needs to go out pretty promptly though :)

One question - trying to follow through all the Kotlin lazy initialization. Where/when does the Radar SDK manage to get a reference to Context?

**Comment by russellcullen** [comment]
Will update to the new identity and user attribute APIs asap, thanks for the heads up.
We get the context in a (no-op) `ContentProvider` like this:
https://firebase.googleblog.com/2016/12/how-does-firebase-initialize-on-android.html

**Comment by samdozor** [comment]
nice! fancy trick/hack :)

**Comment by russellcullen** [comment]
@samdozor We're ready to merge these (both ios and android) PRs now, let us know if you need any changes from us.

**Pull request merged**
